### ISSUE TITLE
Bug: minSdkVersion 19 , even though classes used need API 23 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlecodelabs/slices-basic-codelab#3]
Or at least that's what the IDE says:

![image](https://user-images.githubusercontent.com/5357526/45806848-bae84500-bcca-11e8-8dab-d98edb2ed525.png)

What is correct?

**Comment by AndroidDeveloperLB** [comment]
I think the IDE is wrong, so I made a bug report:

https://issuetracker.google.com/issues/116182832

**Comment by codingjeremy** [comment]
I rewrote the codelab in Kotlin and upped the min SDK. :)
